version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: --port 14703
    ports:
      - "14703:14703"
    volumes:
      - redis-data:/data

  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
