app_env: 'local'
port: 3000

database:
  type: 'postgres'
  host: 'localhost'
  port: '5432'
  username: 'postgres'
  password: 'postgres'
  db_name: 'postgres'

redis:
  host: 'localhost'
  port: 6379

websocketConfig:
  host: 'localhost'
  port: 6379

aws:
  region: 'us-east-1'
  accessKeyId: 'accessKeyId'
  secretAccessKey: 'secretAccessKey' 
  platformApplicationArn: 'platformApplicationArn'