app_env: 'local'
port: 3000

database:
  type: 'postgres'
  host: <%= process.env.DATABASE_HOST %>
  port: '5432'
  username: <%= process.env.DATABASE_USERNAME %>
  password: <%= process.env.DATABASE_PASSWORD %>
  db_name: 'postgres'

redis:
  host: <%= process.env.REDIS_HOST %>
  port: 19635
  username: <%= process.env.REDIS_USERNAME %>
  password: <%= process.env.REDIS_PASSWORD %>

websocketConfig:
  host: <%= process.env.REDIS_HOST %>
  port: 19635
  username: <%= process.env.REDIS_USERNAME %>
  password: <%= process.env.REDIS_PASSWORD %>

aws:
  region: <%= process.env.AWS_REGION %>
  accessKeyId: <%= process.env.AWS_ACCESS_KEY %>
  secretAccessKey: <%= process.env.AWS_SECRET_ACCESS_KEY %>
  platformApplicationArn: <%= process.env.AWS_PLATFORM_APPLICATION_ARN %>

jwt:
  secret: <%= process.env.JWT_SECRET %>
  expireTime: '1d'