export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  WRONG_USER_OR_PASSWORD = 'WRONG_USER_OR_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
}
